spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springreact
    username: ohgiraffers
    password: ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: dkssudgktpdyqksrkdnjdydkssudgktpdyqksrkdnjdy

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

## 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  ## WebConfig에 세팅
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**